application: michaeljferrari
version: 3
runtime: python
api_version: 1

default_expiration: "1h"

handlers:
- url: /img
  static_dir: site/img

- url: /css
  static_dir: site/css

- url: /js
  static_dir: site/js

- url: /xml
  static_dir: site/xml

- url: /swf
  static_dir: site/swf

- url: /(robots\.txt)
  static_files: site/txt/\1
  upload: site/txt/
  
- url: /(.*\.xml)
  static_files: site/xml/\1
  upload: site/xml/.*\.xml

- url: /admin2.*
  script: admin2.py
  login: required

- url: /.*
  script: public.py
